/**
 * Generates public/_redirects and public/_headers from whatever is in public/.
 *
 * Both files were hand-maintained and both silently fell behind when the ten
 * service pages were added: their .html forms kept answering with the
 * platform's built-in 307, and their HTML was never told to revalidate.
 *
 * A 307 is the specific problem. It means "temporary", so a crawler keeps the
 * old URL on file and re-checks it forever - which is exactly what put
 * /index.html and friends in Search Console's "Page with redirect" report. A
 * 301 says the move is permanent, so the old URL is dropped and its link equity
 * moves to the canonical one.
 *
 * Three legacy shapes are covered for every page:
 *
 *   /about.html   ->  /about     the form Google already has on file
 *   /about/       ->  /about     trailing slash, otherwise a 307
 *   /index, /index/ ->  /        both, because /index/ chained 307 -> 307
 *
 * 404.html is deliberately excluded - an error page must not redirect.
 *
 * Run: npm run build:routing
 */
const fs = require('fs');
const path = require('path');

const DIR = process.argv[2] || 'public';
const must = (c, m) => { if (!c) throw new Error(m); };

const pages = fs.readdirSync(DIR)
  .filter(f => f.endsWith('.html') && f !== '404.html')
  .sort();
must(pages.length > 0, 'no pages found in ' + DIR);

// route for a page file: index.html is the site root, everything else drops .html
const routeOf = p => (p === 'index.html' ? '/' : '/' + p.replace(/\.html$/, ''));
const width = Math.max(...pages.map(p => p.length)) + 2;

/* ---------------- _redirects ---------------- */
const rlines = [
  '# GENERATED by tools/build-routing.js - do not edit by hand.',
  '#',
  '# Every legacy form of a URL answers with a permanent redirect to the one',
  '# canonical route. Without these the platform answers .html and trailing-slash',
  '# forms with a 307 Temporary, which tells a crawler to keep the old URL and',
  '# re-check it indefinitely. That is what "Page with redirect" reports are.',
  '#',
  '# 404.html is excluded on purpose: an error page must not redirect.',
  '',
];

for (const p of pages) {
  rlines.push(`/${p}`.padEnd(width + 1) + routeOf(p).padEnd(28) + '301');
}
rlines.push('');
rlines.push('# Trailing-slash forms, which otherwise answer 307.');
for (const p of pages) {
  const r = routeOf(p);
  if (r === '/') continue;                       // "/" has no slashed variant
  rlines.push(`${r}/`.padEnd(width + 1) + r.padEnd(28) + '301');
}
rlines.push('');
rlines.push('# /index and /index/ both resolved through a two-hop 307 chain.');
rlines.push('/index'.padEnd(width + 1) + '/'.padEnd(28) + '301');
rlines.push('/index/'.padEnd(width + 1) + '/'.padEnd(28) + '301');
rlines.push('');

fs.writeFileSync(path.join(DIR, '_redirects'), rlines.join('\n'));

/* ---------------- _headers ---------------- */
const hlines = [
  '# GENERATED by tools/build-routing.js - do not edit by hand.',
  '#',
  '# HTML must revalidate so a deploy is seen immediately rather than served',
  '# stale from an edge or browser cache.',
  '#',
  '# Routes are named explicitly rather than using a catch-all /*, because',
  '# Cloudflare concatenates every matching rule - a catch-all would also strip',
  '# caching from the fonts and images, which should stay cached hard.',
  '',
];

const seen = new Set();
for (const p of pages) {
  for (const route of [routeOf(p), '/' + p]) {
    if (seen.has(route)) continue;
    seen.add(route);
    hlines.push(route);
    hlines.push('  Cache-Control: public, max-age=0, must-revalidate');
  }
}
hlines.push('');

fs.writeFileSync(path.join(DIR, '_headers'), hlines.join('\n'));

/* ---------------- report ---------------- */
const redirCount = rlines.filter(l => /\s301$/.test(l)).length;
const headerCount = seen.size;
must(redirCount === pages.length * 2 + 1, // .html + slashed (minus root) + /index + /index/
  `expected ${pages.length * 2 + 1} redirects, produced ${redirCount}`);

console.log(`  pages:     ${pages.length}`);
console.log(`  _redirects ${redirCount} rules`);
console.log(`  _headers   ${headerCount} routes`);
